### PR TITLE
[ENGSVC-390] Update Actions/Core to Fix Deprecation Issues

### LINKED ISSUE #3: set-env deprecated
See: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

We need to do a couple of updates to bring this up to date.

### PR DESCRIPTION
**Pull request by promiseofcake**
https://teamvsco.atlassian.net/browse/ENGSVC-390
ENGSVC-390

Fixes #3 

See: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Nice thing about this is that we don't need to update all the repos that reference this since they are checking out this action at HEAD.

### CODE REVIEW

File: dist/index.js [hunk 1]
```diff
@@ -3171,9 +3222,17 @@ var ExitCode;
  */
 // eslint-disable-next-line @typescript-eslint/no-explicit-any
 function exportVariable(name, val) {
-    const convertedVal = command_1.toCommandValue(val);
+    const convertedVal = utils_1.toCommandValue(val);
     process.env[name] = convertedVal;
-    command_1.issueCommand('set-env', { name }, convertedVal);
```
Comment (promiseofcake) [inline dist/index.js:3176]: This is the meat of the change but this is also generated so we should 🚀

**Review by ossianpe — APPROVED** [review]
This sounds like a nice security patch to leverage. Thanks for the fix.
